import { Project } from './types';

export const projects: Project[] = [
  {
    id: "tark-crypt",
    title: "Tark Crypt",
    version: "v2.4.0",
    mode: "offline",
    type: "apk",
    status: "active",
    description: "Zero-telemetry local file and media encryption using hardware-accelerated AES-256-GCM.",
    webUrl: "https://crypt.tarkstudio.internal",
    apkUrl: "downloads/tark-crypt-v2.4.0.apk",
    icon: "ShieldCheck",
    category: "Security",
    size: "14.2 MB",
    badgeLabel: "⚡ Offline Local"
  },
  {
    id: "omni-mesh",
    title: "OmniMesh P2P",
    version: "v1.8.2",
    mode: "offline",
    type: "apk",
    status: "active",
    description: "Decentralized mesh communications over local Wi-Fi Direct and Bluetooth LE without internet.",
    webUrl: "https://omni.tarkstudio.internal",
    apkUrl: "downloads/omni-mesh-v1.8.2.apk",
    icon: "Radio",
    category: "Networking",
    size: "22.8 MB",
    badgeLabel: "⚡ Offline P2P"
  },
  {
    id: "vault-core",
    title: "Tark Vault",
    version: "v3.1.0",
    mode: "offline",
    type: "apk",
    status: "active",
    description: "Air-gapped password manager and TOTP authenticator storing encrypted data purely on-device.",
    webUrl: "https://vault.tarkstudio.internal",
    apkUrl: "downloads/tark-vault-v3.1.0.apk",
    icon: "KeyRound",
    category: "Security",
    size: "18.5 MB",
    badgeLabel: "⚡ Offline Local"
  },
  {
    id: "ledger-flow",
    title: "LedgerFlow Mobile",
    version: "v1.2.0",
    mode: "offline",
    type: "apk",
    status: "active",
    description: "Plaintext double-entry accounting ledger with SQLite storage and privacy-guaranteed export.",
    webUrl: "https://ledger.tarkstudio.internal",
    apkUrl: "downloads/ledger-flow-v1.2.0.apk",
    icon: "FileSpreadsheet",
    category: "Finance",
    size: "16.1 MB",
    badgeLabel: "⚡ Offline Local"
  },
  {
    id: "field-topo",
    title: "GeoTracker Field",
    version: "v1.0.0-rc",
    mode: "offline",
    type: "apk",
    status: "locked",
    description: "Vector topographical waypoint navigation and offline contour mapping for backcountry rescue.",
    webUrl: "https://topo.tarkstudio.internal",
    apkUrl: "downloads/geotracker-v1.0.0.apk",
    icon: "Compass",
    category: "Navigation",
    size: "68.4 MB",
    badgeLabel: "⚡ Offline Local"
  },
  {
    id: "cloudsync-studio",
    title: "CloudSync Studio",
    version: "v4.0.2",
    mode: "online",
    type: "website",
    status: "active",
    description: "Real-time collaborative canvas and architecture diagramming with distributed sync engines.",
    webUrl: "https://cloudsync.tarkstudio.dev",
    apkUrl: "downloads/cloudsync-web.apk",
    icon: "Share2",
    category: "Collaboration",
    size: "Cloud Service",
    badgeLabel: "🟢 Online Cloud"
  },
  {
    id: "apex-monitor",
    title: "Apex Metrics Console",
    version: "v2.9.1",
    mode: "online",
    type: "website",
    status: "active",
    description: "Distributed telemetry aggregator with real-time stream graphs and anomaly alert webhooks.",
    webUrl: "https://apex.tarkstudio.dev",
    apkUrl: "downloads/apex-monitor.apk",
    icon: "Activity",
    category: "DevOps",
    size: "Cloud Service",
    badgeLabel: "🟢 Online Cloud"
  },
  {
    id: "byteshare-web",
    title: "ByteShare Web",
    version: "v1.6.0",
    mode: "online",
    type: "website",
    status: "active",
    description: "WebRTC-powered browser-to-browser encrypted high-speed file transfer portal.",
    webUrl: "https://byteshare.tarkstudio.dev",
    apkUrl: "downloads/byteshare-web.apk",
    icon: "Zap",
    category: "Transfer",
    size: "Web Tool",
    badgeLabel: "🟢 Online WebRTC"
  },
  {
    id: "signal-mesh-hub",
    title: "SignalMesh Hub",
    version: "v2.0.0-beta",
    mode: "online",
    type: "website",
    status: "locked",
    description: "Enterprise WebSocket broker dashboard for distributed fleet monitoring and command execution.",
    webUrl: "https://signalhub.tarkstudio.dev",
    apkUrl: "downloads/signal-mesh-hub.apk",
    icon: "Network",
    category: "Infrastructure",
    size: "Cloud Service",
    badgeLabel: "🟢 Online Cloud"
  },
  {
    id: "tark-remote",
    title: "Tark Remote Desk",
    version: "v1.1.0",
    mode: "online",
    type: "apk",
    status: "locked",
    description: "Hardware-accelerated ultra-low-latency remote desktop client with end-to-end SRTP streaming.",
    webUrl: "https://remote.tarkstudio.internal",
    apkUrl: "downloads/tark-remote-v1.1.0.apk",
    icon: "Laptop",
    category: "Remote Access",
    size: "34.0 MB",
    badgeLabel: "🟢 Online Relay"
  },
  {
    id: "neural-forge",
    title: "NeuralForge Studio",
    version: "v2.2.0",
    mode: "hybrid",
    type: "website",
    status: "active",
    description: "Edge ONNX browser inference with optional cloud fallback acceleration for LLMs and vision.",
    webUrl: "https://neuralforge.tarkstudio.dev",
    apkUrl: "downloads/neuralforge.apk",
    icon: "Cpu",
    category: "Machine Learning",
    size: "Hybrid Engine",
    badgeLabel: "🔄 Hybrid Sync"
  },
  {
    id: "synth-recorder",
    title: "WaveCraft DAW",
    version: "v1.4.5",
    mode: "offline",
    type: "apk",
    status: "active",
    description: "Low-latency polyphonic synthesizer and multitrack audio recorder with zero background telemetry.",
    webUrl: "https://wavecraft.tarkstudio.internal",
    apkUrl: "downloads/wavecraft-v1.4.5.apk",
    icon: "AudioLines",
    category: "Audio",
    size: "42.3 MB",
    badgeLabel: "⚡ Offline Local"
  }
];

export default projects;
